export const columnsArr = [
  {
    title: '序号',
    dataIndex: 'key',
    width: '70px',
    fixed: 'left',
  },
  {
    title: '时间',
    dataIndex: 'repTime',
    width: '220px',
    editable: true,
  },
  {
    title: '任务指派领导',
    dataIndex: 'taskAssignLeader',
    width: '150px',
    editable: true,
  },
  // {
  //   title: '来源',
  //   dataIndex: 'source',
  //   width: '150px',
  //   editable: true,
  // },
  {
    title: '类别',
    dataIndex: 'categoryIds',
    width: '140px',
    editable: true,
  },
  {
    title: '用车审核人',
    dataIndex: 'carUseAuditor',
    width: '150px',
    editable: true,
  },
  {
    title: '任务执行人',
    dataIndex: 'taskExecutor',
    width: '150px',
    editable: true,
  },
  // {
  //   title: '汇报人',
  //   dataIndex: 'reporters',
  //   width: '150px',
  //   editable: true,
  // },
  // {
  //   title: '同行人',
  //   dataIndex: 'peers',
  //   width: '140px',
  //   editable: true,
  // },
  // {
  //   title: '记录人',
  //   dataIndex: 'loggers',
  //   width: '140px',
  //   editable: true,
  // },
  {
    title: '详细情况',
    dataIndex: 'repDetail',
    width: '160px',
    editable: true,
  },
  {
    title: '是否反馈',
    dataIndex: 'isFeedback',
    width: '90px',
    editable: true,
  },
  {
    title: '反馈内容',
    dataIndex: 'feedbackContext',
    width: '160px',
    editable: true,
  },
  {
    title: '抓捕人数',
    dataIndex: 'arrestNum',
    width: '110px',
    editable: true,
  },
  {
    title: '任务地点',
    dataIndex: 'taskLocation',
    width: '140px',
    editable: true,
  },
  {
    title: '备注',
    dataIndex: 'remark',
    width: '140px',
    editable: true,
  },
];
